apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: nodejs-template
  title: nodejs
  description: Create a simple node js project
  tags:
    - recommended
    - nodejs
spec:
  owner: service@example.com
  type: service
  parameters:
    - title: Provide component information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
        description:
          title: Description
          type: string
          description: Add a description to explain the component
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
        title: Repository Location
        type: string
        ui:field: RepoUrlPicker
        ui:options:
          allowedHosts:
            - dev.azure.com

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
        values:
          component_id: '{{ parameters.component_id }}'
          description: '{{ parameters.description }}'
          owner: '{{ parameters.owner }}'
          destination: '{{ parseRepoUr1 parameters.repoUrl }}'
    - id: publish
      name: Publish
      action: publish:azure
      input:
        allowedHosts: ['dev.azure.com']
        description: 'This is {{ parameters.component_id }}'
        repoUrl: '{{ parameters.repoUr1 }}'
    - id: register
      name: Register
      action: catalog:register
      input:
        repotContentUrl: '{{ steps.publish.output.removeUrl }}'
        catalogInfoPath: '/catalog-info.yaml'
  output:
    remoteUrl: '{{ steps.publish.output.rentityRef }}'
    entityRef: '{{steps.register.output.entityRef}}'



